
-- Drop STATE_CITY
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STATE_CITY]') AND type in (N'U'))
DROP TABLE [dbo].[STATE_CITY]
GO

DELETE FROM ZIPCODE_CITY_COUNTY_POPULATION

-- Delete all data